# Site settings
title: "Jiankai"
description: "My personal website."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jiankai Jin"
resume_title:                   "PhD candidate of unimelb"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jinkai2525@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi, this is Jiankai, a PhD student from the University of Melbourne. I was also a machine learning engineer focusing on recommendation algorithms before.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_publication:     true
resume_section_experience:      true
resume_section_skills:          true
resume_section_awards:          true
# resume_section_projects:        true
# resume_section_recognition:     true
# resume_section_links:           false
# resume_section_associations:    false


# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jason-jiankai"
  resume_twitter_url:           "https://twitter.com/jiankai_jin"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jin-jiankai-3a5750119/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
